# Generated by Django 3.2 on 2024-12-02 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_system', '0006_auto_20241202_1431'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name': 'Медиа', 'verbose_name_plural': 'Медиа'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Уведомление', 'verbose_name_plural': 'Уведомления'},
        ),
        migrations.AlterModelOptions(
            name='statuscode',
            options={'verbose_name': 'Код статуса', 'verbose_name_plural': 'Коды статусов'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Подкатегория', 'verbose_name_plural': 'Подкатегории'},
        ),
        migrations.AlterModelOptions(
            name='supportticket',
            options={'verbose_name': 'Тикет поддержки', 'verbose_name_plural': 'Тикеты поддержки'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Тикет', 'verbose_name_plural': 'Тикеты'},
        ),
    ]
