# Generated by Django 3.2 on 2024-12-11 07:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_system', '0023_auto_20241208_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='address',
        ),
        migrations.RemoveField(
            model_name='ticketaudit',
            name='address',
        ),
        migrations.AddField(
            model_name='ticket',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9, verbose_name='Широта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='longtitude',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9, verbose_name='Долгота'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketaudit',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9, verbose_name='Широта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketaudit',
            name='longtitude',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9, verbose_name='Долгота'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 11, 7, 48, 23, 372917, tzinfo=utc), verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 11, 7, 48, 23, 370811, tzinfo=utc), verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 11, 7, 48, 23, 370811, tzinfo=utc), verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='ticketaudit',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 11, 7, 48, 23, 370811, tzinfo=utc), verbose_name='Создано'),
        ),
    ]
