# Generated by Django 3.2 on 2024-12-17 15:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_system', '0030_auto_20241214_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 17, 15, 6, 47, 872543, tzinfo=utc), verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='category',
            name='source',
            field=models.ImageField(null=True, upload_to='categories/f', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='media',
            name='source',
            field=models.ImageField(upload_to='media/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 17, 15, 6, 47, 875132, tzinfo=utc), verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 17, 15, 6, 47, 875646, tzinfo=utc), verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 17, 15, 6, 47, 872543, tzinfo=utc), verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='source',
            field=models.ImageField(null=True, upload_to='subcategories/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 17, 15, 6, 47, 873060, tzinfo=utc), verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 17, 15, 6, 47, 873060, tzinfo=utc), verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='ticketaudit',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 17, 15, 6, 47, 873060, tzinfo=utc), verbose_name='Создано'),
        ),
    ]
