# Generated by Django 3.2 on 2025-01-02 05:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_system', '0033_auto_20241230_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 5, 31, 21, 860315, tzinfo=utc), verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 5, 31, 21, 863314, tzinfo=utc), verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 5, 31, 21, 863314, tzinfo=utc), verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 5, 31, 21, 860315, tzinfo=utc), verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 5, 31, 21, 861821, tzinfo=utc), verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 5, 31, 21, 861821, tzinfo=utc), verbose_name='Создано'),
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='media',
        ),
        migrations.AddField(
            model_name='ticket',
            name='media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket_system.media', verbose_name='Медиа'),
        ),
        migrations.AlterField(
            model_name='ticketaudit',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 5, 31, 21, 861821, tzinfo=utc), verbose_name='Создано'),
        ),
        migrations.RemoveField(
            model_name='ticketaudit',
            name='media',
        ),
        migrations.AddField(
            model_name='ticketaudit',
            name='media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket_system.media', verbose_name='Медиа'),
        ),
    ]
