# Generated by Django 3.2 on 2025-01-03 06:24

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_system', '0035_auto_20250102_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 6, 24, 36, 427528, tzinfo=utc), verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='category',
            name='source',
            field=models.ImageField(null=True, upload_to='categories/media/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='media',
            name='source',
            field=models.ImageField(upload_to='ticket/media/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='media',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='ticket_system.ticket'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 6, 24, 36, 429315, tzinfo=utc), verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 6, 24, 36, 430329, tzinfo=utc), verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 6, 24, 36, 427528, tzinfo=utc), verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='source',
            field=models.ImageField(null=True, upload_to='subcategories/media/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 6, 24, 36, 427528, tzinfo=utc), verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 6, 24, 36, 427528, tzinfo=utc), verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='ticketaudit',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 6, 24, 36, 427528, tzinfo=utc), verbose_name='Создано'),
        ),
        migrations.CreateModel(
            name='MediaAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('ticket_audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='ticket_system.ticketaudit')),
            ],
            options={
                'verbose_name': ('Медиа для аудита',),
                'verbose_name_plural': 'Медиа для аудита',
            },
        ),
    ]
