# Generated by Django 3.2 on 2024-12-30 03:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20241214_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeratorSetuped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 12, 30, 3, 32, 57, 974230, tzinfo=utc))),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Админ', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Пользователь', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
