# Generated by Django 3.2 on 2025-01-02 05:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_moderatorsetuped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderatorsetuped',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 5, 31, 21, 859321, tzinfo=utc)),
        ),
    ]
