# Generated by Django 3.2 on 2024-11-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20241105_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customabstractuser',
            name='second_name',
        ),
        migrations.AlterField(
            model_name='customabstractuser',
            name='last_name',
            field=models.CharField(max_length=40, verbose_name='Фамилия'),
        ),
    ]
