# Generated by Django 3.2 on 2024-12-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20241114_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='customabstractuser',
            name='given_name',
            field=models.CharField(default=1, max_length=40, verbose_name='Отчество'),
            preserve_default=False,
        ),
    ]
