# Generated by Django 3.2 on 2024-12-02 17:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customabstractuser_given_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customabstractuser',
            name='rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Рейтинг'),
        ),
    ]
