# Generated by Django 3.2 on 2024-11-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_system', '0003_auto_20241114_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default=1, max_length=500, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
