# Generated by Django 3.2 on 2024-12-02 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_system', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='source',
            field=models.ImageField(default=1, upload_to='', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Тип тикета')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('source', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_system.category')),
            ],
        ),
    ]
