# Generated by Django 3.2 on 2024-12-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_system', '0007_auto_20241202_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='address',
            field=models.CharField(max_length=50, null=True, verbose_name='Адрес проблемы'),
        ),
    ]
