# Generated by Django 3.2 on 2024-12-03 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_system', '0010_auto_20241203_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket_system.subcategory'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket_system.subcategory'),
        ),
    ]
