# Generated by Django 3.2 on 2024-12-04 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket_system', '0011_auto_20241203_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Тело')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('address', models.CharField(max_length=100, null=True, verbose_name='Адрес проблемы')),
                ('time', models.DateTimeField(null=True, verbose_name='Время проишествия')),
                ('edited', models.BooleanField(default=False, verbose_name='Редактировано')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket_system.category')),
                ('media', models.ManyToManyField(null=True, to='ticket_system.Media', verbose_name='Медиа')),
                ('status_code', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='ticket_system.statuscode', verbose_name='Статус')),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket_system.subcategory')),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket_system.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Изменения тикета',
                'verbose_name_plural': 'Изменения тикетов',
            },
        ),
    ]
