# Generated by Django 3.2 on 2024-12-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_system', '0012_ticketaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='Черновик'),
        ),
        migrations.AddField(
            model_name='ticketaudit',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='Черновик'),
        ),
    ]
