# Generated by Django 3.2 on 2024-12-15 11:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_system', '0030_auto_20241214_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 15, 11, 37, 34, 812150, tzinfo=utc), verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='category',
            name='source',
            field=models.ImageField(null=True, upload_to='categories/f', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='media',
            name='source',
            field=models.ImageField(upload_to='media/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 15, 11, 37, 34, 814907, tzinfo=utc), verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 15, 11, 37, 34, 815259, tzinfo=utc), verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 15, 11, 37, 34, 812511, tzinfo=utc), verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='source',
            field=models.ImageField(null=True, upload_to='subcategories/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 15, 11, 37, 34, 812779, tzinfo=utc), verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 15, 11, 37, 34, 812779, tzinfo=utc), verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='ticketaudit',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 15, 11, 37, 34, 812779, tzinfo=utc), verbose_name='Создано'),
        ),
    ]
